const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const SUPABASE_URL='https://dtnznddoqyupuzilsgrb.supabase.co';
const SUPABASE_PUBLISHABLE_KEY='sb_publishable_R0xQi6sQS_X4RFpakL6a2A_wXRWoTjZ';
const supabaseClient=window.supabase?.createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY);
const palettes=['linear-gradient(135deg,#f7e8a2,#dfbd48)','linear-gradient(135deg,#fffef7,#d8d6cd)','linear-gradient(135deg,#e69775,#a94e3d)','linear-gradient(135deg,#eee1ca,#b8a27d)','radial-gradient(circle at 25% 30%,#f7f0d5 0 7%,transparent 8%),linear-gradient(135deg,#b8d6d0,#689aa2)','linear-gradient(135deg,#bed0db,#718da1)'];
const starter=[['Butter yellow tank','top'],['White linen shirt','top'],['Terracotta skirt','bottom'],['Wide-leg trousers','bottom'],['Blue floral dress','dress'],['Light denim jacket','outerwear'],['Black sandals','shoe'],['Woven tote','accessory']].map((x,i)=>({id:i+1,name:x[0],category:x[1],colour:'',image:'',fallback:palettes[i%palettes.length],packed:false}));
let state=JSON.parse(localStorage.getItem('tripClosetV2')||'null')||{trip:null,clothes:starter,looks:[],checklist:['Passport','Phone charger','Toiletries','Medication','Sunglasses','Reusable water bottle'].map((text,i)=>({id:i+1,text,checked:false}))};
let filter='all',selected=[],pendingImage='',assigning=null,currentUser=null,syncTimer;
function persist(){localStorage.setItem('tripClosetV2',JSON.stringify(state));if(currentUser){clearTimeout(syncTimer);syncTimer=setTimeout(saveCloudState,450)}}
async function saveCloudState(){if(!currentUser)return;await supabaseClient.from('trip_closet_states').upsert({user_id:currentUser.id,data:state,updated_at:new Date().toISOString()})}
async function loadCloudState(){const {data,error}=await supabaseClient.from('trip_closet_states').select('data').eq('user_id',currentUser.id).maybeSingle();if(data?.data){state=data.data;localStorage.setItem('tripClosetV2',JSON.stringify(state))}else if(!error||error.code==='PGRST116')await saveCloudState();else console.warn('Cloud sync needs the supplied Supabase SQL setup.',error.message)}
const piece=id=>state.clothes.find(x=>x.id===id); const img=x=>x.image?`url(${x.image})`:x.fallback;
function dateList(){if(!state.trip)return[];let out=[],d=new Date(state.trip.start+'T12:00:00'),end=new Date(state.trip.end+'T12:00:00');while(d<=end){out.push(new Date(d));d.setDate(d.getDate()+1)}return out}
function dayKey(d){return d.toISOString().slice(0,10)}
function weather(d){let live=state.trip?.weather?.[dayKey(d)];if(live)return live;const temps=[25,27,24,22,26,28,23],t=temps[d.getDate()%temps.length];return {t,icon:t>25?'☀':'☼'}}
function formatDate(d){return d.toLocaleDateString(undefined,{weekday:'short',month:'short',day:'numeric'})}
function renderTrip(){const t=state.trip;if(!t){$('#sideTrip').textContent='Create your trip';$('#sideDates').textContent='Choose dates to begin';$('#pageTitle').innerHTML='Ready when <em>you are.</em>';return}const days=dateList();$('#sideTrip').textContent=t.name;$('#sideDates').textContent=`${formatDate(days[0])} — ${formatDate(days.at(-1))}`;$('#pageTitle').innerHTML=`Outfits for <em>${t.destination}</em>`;$('#weatherHeadline').textContent=`${t.destination} is on the calendar.`;$('#readinessNote').textContent=`${days.length} days to explore — build looks, then mark each one packed.`}
function lookVisual(ids,extra=''){let items=ids.map(piece).filter(Boolean);return `<div class="visual-look ${extra}">${items.map(x=>`<i class="piece-thumb" style="background-image:${img(x)}"></i>`).join('')}</div>`}
function renderItinerary(){const root=$('#itinerary'),days=dateList();if(!days.length){root.innerHTML='<div class="empty-state">Create a trip to see your outfit itinerary.</div>';renderReadiness();return}root.innerHTML=days.map((d,i)=>{let key=dayKey(d),saved=state.trip.schedule?.[key],look=saved&&state.looks.find(l=>l.id===saved.lookId),w=weather(d);return `<article class="day-card ${i===0?'today':''}"><div class="day-date">${formatDate(d).split(',')[0]}<strong>${d.getDate()}</strong></div><div class="weather">${w.icon}<small>${w.t}°C</small></div>${look?`${lookVisual(look.pieces)}<div class="look-title">${look.name}</div><div class="look-detail">${look.pieces.map(piece).filter(Boolean).map(x=>x.name).join(' + ')}</div>${look.packed?'<div class="packed-tag">✓ LOOK PACKED</div>':''}<div class="day-actions"><button class="small-btn" onclick="openAssign('${key}')">Swap look</button><button class="small-btn" onclick="markLookPacked(${look.id})">${look.packed?'Unpack':'Mark packed'}</button><button class="small-btn" onclick="clearDay('${key}')">Clear</button></div>`:`<div class="empty-state" style="margin-top:17px;padding:28px 10px">No look planned<br><button class="small-btn" style="margin-top:9px" onclick="openAssign('${key}')">Add an outfit</button></div>`}</article>`}).join('');renderReadiness()}
function renderReadiness(){const days=dateList(),scheduled=days.filter(d=>state.trip?.schedule?.[dayKey(d)]).length,packed=state.clothes.filter(x=>x.packed).length,needed=new Set(Object.values(state.trip?.schedule||{}).flatMap(s=>state.looks.find(l=>l.id===s.lookId)?.pieces||[])).size;let ready=days.length?Math.round((scheduled/days.length*.65)+(needed?packed/needed*35:0)):0;ready=Math.min(100,ready);$('#readyNum').textContent=ready+'%';$('#readyProgress').value=ready;$('#readyText').textContent=days.length?`${scheduled} of ${days.length} days styled · ${packed} pieces packed`:'No trip planned yet'}
function renderCloset(){const items=state.clothes.filter(x=>filter==='all'||x.category===filter);$('#closetGrid').innerHTML=items.map(x=>`<article class="piece"><div class="piece-image" style="background-image:${img(x)}"><button onclick="removePiece(${x.id})" title="Remove">×</button></div><p>${x.name}</p><span>${x.category}${x.colour?' · '+x.colour:''}</span><label><input type="checkbox" ${x.packed?'checked':''} onchange="togglePacked(${x.id})"> Packed</label></article>`).join('')||'<div class="empty-state">No matching pieces yet.</div>';$('#closetCount').textContent=state.clothes.length;$('#packedCount').textContent=`${state.clothes.filter(x=>x.packed).length} packed`}
function renderBuilder(){const cats=['top','bottom','dress','outerwear','shoe','accessory'];$('#builderOptions').innerHTML=cats.map(cat=>{let options=state.clothes.filter(x=>x.category===cat);return options.length?options.map(x=>`<button class="choice ${selected.includes(x.id)?'selected':''}" onclick="pick(${x.id})"><div style="background-image:${img(x)}"></div>${x.name}</button>`).join(''):''}).join('');$('#lookBoard').innerHTML=selected.length?lookVisual(selected):'<p>Your selected pieces<br><small>will appear here</small></p>'}
function renderLooks(){const root=$('#savedLooks');root.innerHTML=state.looks.length?state.looks.map(l=>`<article class="saved-card" onclick="loadLook(${l.id})">${lookVisual(l.pieces)}<b>${l.name}</b></article>`).join(''):'<small style="color:var(--muted)">Save a look from the builder to reuse it.</small>'}
function renderPacking(){const root=$('#packingList');root.innerHTML=state.checklist.map(x=>`<div class="pack-item ${x.checked?'checked':''}"><input type="checkbox" ${x.checked?'checked':''} onchange="checkItem(${x.id})"><span>${x.text}</span><button onclick="removeCheck(${x.id})">×</button></div>`).join('')}
function render(){renderTrip();renderItinerary();renderCloset();renderBuilder();renderLooks();renderPacking()}
async function getWeather(){if(!state.trip?.destination)return;try{let geo=await fetch(`https://geocoding-api.open-meteo.com/v1/search?name=${encodeURIComponent(state.trip.destination)}&count=1&language=en&format=json`).then(r=>r.json()),place=geo.results?.[0];if(!place)throw Error('No place');let maxDate=new Date();maxDate.setDate(maxDate.getDate()+16);let start=state.trip.start,end=state.trip.end;if(new Date(start)>maxDate)return;let limit=new Date(Math.min(new Date(end+'T12:00'),maxDate));let data=await fetch(`https://api.open-meteo.com/v1/forecast?latitude=${place.latitude}&longitude=${place.longitude}&daily=weather_code,temperature_2m_max&timezone=auto&start_date=${start}&end_date=${dayKey(limit)}`).then(r=>r.json());state.trip.weather={};(data.daily?.time||[]).forEach((date,i)=>{let code=data.daily.weather_code[i],icons=code<=1?'☀':code<=3?'☼':code<=67?'☁':'☂';state.trip.weather[date]={t:Math.round(data.daily.temperature_2m_max[i]),icon:icons}});persist();renderItinerary();$('#weatherHeadline').textContent=`Live forecast loaded for ${place.name}.`}catch{ $('#weatherHeadline').textContent='Typical weather is shown for your trip.' }}
function saveTrip(){let name=$('#tripName').value.trim(),destination=$('#tripDestination').value.trim(),start=$('#tripStart').value,end=$('#tripEnd').value,err=$('#tripError'),days=(new Date(end+'T12:00')-new Date(start+'T12:00'))/864e5+1;if(!name||!destination||!start||!end||days<2||days>90){event.preventDefault();err.textContent='Please enter a trip between 2 and 90 days.';err.className='form-note error';return}state.trip={name,destination,start,end,schedule:state.trip?.schedule||{},weather:{}};persist();render();getWeather()}
function savePiece(){let name=$('#itemName').value.trim();if(!name){event.preventDefault();return}state.clothes.unshift({id:Date.now(),name,category:$('#itemCategory').value,colour:$('#itemColour').value.trim(),image:pendingImage,fallback:palettes[state.clothes.length%palettes.length],packed:false});pendingImage='';persist();renderCloset();renderBuilder()}
function openAssign(key){if(!state.trip)return;assigning=key;let options=state.looks.map(l=>`<option value="${l.id}">${l.name}</option>`).join('');if(!options){selected=[];$('#lookName').value='';location.hash='builder';return}$('#assignLookSelect').innerHTML=options;$('#assignDate').innerHTML=dateList().map(d=>`<option value="${dayKey(d)}" ${dayKey(d)===key?'selected':''}>${formatDate(d)}</option>`).join('');$('#assignDialog').showModal()}
function confirmAssign(){state.trip.schedule[$('#assignDate').value]={lookId:Number($('#assignLookSelect').value)};persist();renderItinerary()}
function suggest(file){let n=file.name.replace(/[-_]/g,' ').replace(/\.[^.]+$/,'').trim(),s=n.toLowerCase(),cat=s.includes('dress')?'dress':s.match(/pants|jean|skirt|short|trouser/)?'bottom':s.match(/shoe|boot|sandal|heel|sneaker/)?'shoe':s.match(/jacket|coat|blazer|cardigan/)?'outerwear':s.match(/bag|belt|hat|scarf|jewel/)?'accessory':'top';return {n:n.replace(/\b\w/g,c=>c.toUpperCase()),cat}}
function autoPlan(){if(!state.trip)return $('#tripDialog').showModal();let available=state.looks;if(!available.length){let tops=state.clothes.filter(x=>x.category==='top'),bottoms=state.clothes.filter(x=>x.category==='bottom'),dresses=state.clothes.filter(x=>x.category==='dress'),shoes=state.clothes.filter(x=>x.category==='shoe');for(let i=0;i<Math.max(1,Math.min(5,tops.length+ dresses.length));i++){let ids=(dresses[i%dresses.length]?[dresses[i%dresses.length]?.id]:[tops[i%tops.length]?.id,bottoms[i%bottoms.length]?.id]).filter(Boolean);if(shoes.length)ids.push(shoes[i%shoes.length].id);if(ids.length)state.looks.push({id:Date.now()+i,name:`Suggested look ${i+1}`,pieces:ids,packed:false})}available=state.looks}dateList().forEach((d,i)=>{let k=dayKey(d);if(!state.trip.schedule[k]&&available.length)state.trip.schedule[k]={lookId:available[i%available.length].id}});persist();render()}
function pick(id){let x=piece(id),old=selected.findIndex(y=>piece(y)?.category===x.category);if(selected.includes(id))selected=selected.filter(x=>x!==id);else{if(old>=0)selected.splice(old,1);selected.push(id)}renderBuilder()}
function loadLook(id){selected=[...state.looks.find(l=>l.id===id).pieces];$('#lookName').value=state.looks.find(l=>l.id===id).name;renderBuilder();location.hash='builder'}
function markLookPacked(id){let l=state.looks.find(x=>x.id===id);l.packed=!l.packed;l.pieces.forEach(id=>{let p=piece(id);if(p)p.packed=l.packed});persist();render()}
function clearDay(k){delete state.trip.schedule[k];persist();renderItinerary()}
function removePiece(id){state.clothes=state.clothes.filter(x=>x.id!==id);selected=selected.filter(x=>x!==id);persist();renderCloset();renderBuilder()}
function togglePacked(id){piece(id).packed=!piece(id).packed;persist();renderCloset();renderReadiness()}
function checkItem(id){let x=state.checklist.find(x=>x.id===id);x.checked=!x.checked;persist();renderPacking()}
function removeCheck(id){state.checklist=state.checklist.filter(x=>x.id!==id);persist();renderPacking()}
window.openAssign=openAssign;window.markLookPacked=markLookPacked;window.clearDay=clearDay;window.pick=pick;window.loadLook=loadLook;window.removePiece=removePiece;window.togglePacked=togglePacked;window.checkItem=checkItem;window.removeCheck=removeCheck;
$('#newTrip').onclick=$('#editTrip').onclick=()=>$('#tripDialog').showModal();$('#saveTrip').onclick=saveTrip;$('#autoPlan').onclick=autoPlan;$('#printPlan').onclick=()=>window.print();$('#addItem').onclick=()=>$('#fileInput').click();$('#fileInput').onchange=e=>{let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{pendingImage=r.result;let s=suggest(f);$('#itemName').value=s.n;$('#itemCategory').value=s.cat;$('#preview').style.backgroundImage=`url(${pendingImage})`;$('#preview').textContent='';$('#itemDialog').showModal()};r.readAsDataURL(f)};$('#saveItem').onclick=savePiece;$('#randomize').onclick=()=>{let by=Object.values(state.clothes.reduce((a,x)=>((a[x.category]??=[]).push(x),a),{}));selected=by.map(a=>a[Math.floor(Math.random()*a.length)].id);renderBuilder()};$('#saveLook').onclick=()=>{if(!selected.length)return;state.looks.push({id:Date.now(),name:$('#lookName').value.trim()||'Untitled look',pieces:[...selected],packed:false});persist();renderLooks();$('#lookName').value=''};$('#assignLook').onclick=()=>{if(selected.length){let l={id:Date.now(),name:$('#lookName').value.trim()||'Untitled look',pieces:[...selected],packed:false};state.looks.push(l);persist();renderLooks()}openAssign(dateList()[0]?dayKey(dateList()[0]):'')};$('#confirmAssign').onclick=confirmAssign;$('#addChecklist').onclick=()=>{let t=prompt('Add a packing item');if(t?.trim()){state.checklist.push({id:Date.now(),text:t.trim(),checked:false});persist();renderPacking()}};$$('#filters button').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;$$('#filters button').forEach(x=>x.classList.toggle('active',x===b));renderCloset()});
$('#loginForm').onsubmit=async e=>{e.preventDefault();let email=$('#loginEmail').value.trim(),message=$('#loginMessage');message.textContent='Sending your secure sign-in link…';let {error}=await supabaseClient.auth.signInWithOtp({email,options:{emailRedirectTo:window.location.href}});message.textContent=error?error.message:'Check your email and open the sign-in link on this device.'};$('#signOut').onclick=()=>supabaseClient.auth.signOut();
async function start(){$('#appShell').style.display='none';$('#authGate').classList.add('visible');if(!supabaseClient){$('#loginMessage').textContent='Could not load secure sign-in. Check your connection and refresh.';return}let {data:{session}}=await supabaseClient.auth.getSession();if(!session)return;currentUser=session.user;await loadCloudState();$('#authGate').classList.remove('visible');$('#appShell').style.display='flex';render()}supabaseClient?.auth.onAuthStateChange((_event,session)=>{if(session&&!currentUser)location.reload();if(!session&&currentUser)location.reload()});start();
