const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
document.addEventListener('click',event=>{let close=event.target.closest?.('dialog .x');if(close){event.preventDefault();close.closest('dialog').close()}},true);
const palettes=['linear-gradient(135deg,#f7e8a2,#dfbd48)','linear-gradient(135deg,#fffef7,#d8d6cd)','linear-gradient(135deg,#e69775,#a94e3d)','linear-gradient(135deg,#eee1ca,#b8a27d)','radial-gradient(circle at 25% 30%,#f7f0d5 0 7%,transparent 8%),linear-gradient(135deg,#b8d6d0,#689aa2)','linear-gradient(135deg,#bed0db,#718da1)'];
const starter=[['Butter yellow tank','top'],['White linen shirt','top'],['Terracotta skirt','bottom'],['Wide-leg trousers','bottom'],['Blue floral dress','dress'],['Light denim jacket','outerwear'],['Black sandals','shoe'],['Woven tote','accessory']].map((x,i)=>({id:i+1,name:x[0],category:x[1],colour:'',image:'',fallback:palettes[i%palettes.length],packed:false}));
const samplePacking=[['Documents','Passport'],['Documents','Boarding pass / tickets'],['Documents','Travel insurance info'],['Documents',"ID / driver's license"],['Electronics','Phone charger'],['Electronics','Power adapter'],['Electronics','Headphones'],['Electronics','Camera'],['Toiletries','Toothbrush & toothpaste'],['Toiletries','Medications'],['Toiletries','Sunscreen'],['Toiletries','Skincare'],['Extras','Umbrella'],['Extras','Reusable water bottle'],['Extras','Daypack']];
let state=JSON.parse(localStorage.getItem('tripClosetV2')||'null')||{trip:null,clothes:starter,looks:[],checklist:samplePacking.map(([group,text],i)=>({id:i+1,group,text,checked:false}))};
if(!localStorage.getItem('tripClosetPackingSamplesV1')){let names=new Set(state.checklist.map(x=>x.text.toLowerCase()));samplePacking.forEach(([group,text],i)=>{if(!names.has(text.toLowerCase()))state.checklist.push({id:Date.now()+i,group,text,checked:false})});localStorage.setItem('tripClosetPackingSamplesV1','true');localStorage.setItem('tripClosetV2',JSON.stringify(state))}
if(!state.packingSections){state.packingSections=[...new Set([...samplePacking.map(x=>x[0]),...state.checklist.map(x=>x.group||'Extras')])];localStorage.setItem('tripClosetV2',JSON.stringify(state))}
let filter='all',selected=[],pendingImage='',assigning=null,editingItemId=null;
const persist=()=>localStorage.setItem('tripClosetV2',JSON.stringify(state));
const piece=id=>state.clothes.find(x=>x.id===id); const img=x=>x.image?`url(${x.image})`:x.fallback;
function dateList(){if(!state.trip)return[];let out=[],d=new Date(state.trip.start+'T12:00:00'),end=new Date(state.trip.end+'T12:00:00');while(d<=end){out.push(new Date(d));d.setDate(d.getDate()+1)}return out}
function dayKey(d){return d.toISOString().slice(0,10)}
function weather(d){let live=state.trip?.weather?.[dayKey(d)];if(live)return live;const temps=[25,27,24,22,26,28,23],t=temps[d.getDate()%temps.length];return {t,icon:t>25?'☀':'☼'}}
function formatDate(d){return d.toLocaleDateString(undefined,{weekday:'short',month:'short',day:'numeric'})}
function renderTrip(){const t=state.trip;if(!t){$('#sideTrip').textContent='Create your trip';$('#sideDates').textContent='Choose dates to begin';$('#pageTitle').innerHTML='Ready when <em>you are.</em>';return}const days=dateList();$('#sideTrip').textContent=t.name;$('#sideDates').textContent=`${formatDate(days[0])} — ${formatDate(days.at(-1))}`;$('#pageTitle').innerHTML=`Outfits for <em>${t.destination}</em>`;$('#weatherHeadline').textContent=`${t.destination} is on the calendar.`;$('#readinessNote').textContent=`${days.length} days to explore — build looks, then mark each one packed.`}
function lookVisual(ids,extra=''){let items=ids.map(piece).filter(Boolean);return `<div class="visual-look ${extra}">${items.map(x=>`<i class="piece-thumb" style="background-image:${img(x)}"></i>`).join('')}</div>`}
function renderItinerary(){const root=$('#itinerary'),days=dateList();if(!days.length){root.innerHTML='<div class="empty-state">Create a trip to see your outfit itinerary.</div>';renderReadiness();return}root.innerHTML=days.map((d,i)=>{let key=dayKey(d),saved=state.trip.schedule?.[key],look=saved&&state.looks.find(l=>l.id===saved.lookId),w=weather(d);return `<article class="day-card ${i===0?'today':''}"><div class="day-date">${formatDate(d).split(',')[0]}<strong>${d.getDate()}</strong></div><div class="weather">${w.icon}<small>${w.t}°C</small></div>${look?`${lookVisual(look.pieces)}<div class="look-title">${look.name}</div><div class="look-detail">${look.pieces.map(piece).filter(Boolean).map(x=>x.name).join(' + ')}</div>${look.packed?'<div class="packed-tag">✓ LOOK PACKED</div>':''}<div class="day-actions"><button class="small-btn" onclick="openAssign('${key}')">Swap look</button><button class="small-btn" onclick="markLookPacked(${look.id})">${look.packed?'Unpack':'Mark packed'}</button><button class="small-btn" onclick="clearDay('${key}')">Clear</button></div>`:`<div class="empty-state" style="margin-top:17px;padding:28px 10px">No look planned<br><button class="small-btn" style="margin-top:9px" onclick="openAssign('${key}')">Add an outfit</button></div>`}</article>`}).join('');renderReadiness()}
function renderReadiness(){const days=dateList(),scheduled=days.filter(d=>state.trip?.schedule?.[dayKey(d)]).length,packed=state.clothes.filter(x=>x.packed).length,needed=new Set(Object.values(state.trip?.schedule||{}).flatMap(s=>state.looks.find(l=>l.id===s.lookId)?.pieces||[])).size;let ready=days.length?Math.round((scheduled/days.length*.65)+(needed?packed/needed*35:0)):0;ready=Math.min(100,ready);$('#readyNum').textContent=ready+'%';$('#readyProgress').value=ready;$('#readyText').textContent=days.length?`${scheduled} of ${days.length} days styled · ${packed} pieces packed`:'No trip planned yet'}
function renderCloset(){const items=state.clothes.filter(x=>filter==='all'||x.category===filter);$('#closetGrid').innerHTML=items.map(x=>`<article class="piece"><div class="piece-image" style="background-image:${img(x)}"><button style="right:34px" onclick="editPiece(${x.id})" title="Edit details">✎</button><button onclick="removePiece(${x.id})" title="Remove">×</button></div><p>${x.name}</p><span>${x.category}${x.colour?' · '+x.colour:''}</span><label><input type="checkbox" ${x.packed?'checked':''} onchange="togglePacked(${x.id})"> Packed</label></article>`).join('')||'<div class="empty-state">No matching pieces yet.</div>';$('#closetCount').textContent=state.clothes.length;$('#packedCount').textContent=`${state.clothes.filter(x=>x.packed).length} packed`}
function renderBuilder(){const cats=['top','bottom','dress','outerwear','shoe','accessory'];$('#builderOptions').innerHTML=cats.map(cat=>{let options=state.clothes.filter(x=>x.category===cat);return options.length?options.map(x=>`<button class="choice ${selected.includes(x.id)?'selected':''}" onclick="pick(${x.id})"><div style="background-image:${img(x)}"></div>${x.name}</button>`).join(''):''}).join('');$('#lookBoard').innerHTML=selected.length?lookVisual(selected):'<p>Your selected pieces<br><small>will appear here</small></p>'}
function renderLooks(){const root=$('#savedLooks');root.innerHTML=state.looks.length?state.looks.map(l=>`<article class="saved-card" onclick="loadLook(${l.id})">${lookVisual(l.pieces)}<b>${l.name}</b></article>`).join(''):'<small style="color:var(--muted)">Save a look from the builder to reuse it.</small>'}
function renderPacking(){const root=$('#packingList'),groups={};state.packingSections.forEach(group=>groups[group]=[]);state.checklist.forEach(x=>((groups[x.group||'Extras']??=[]).push(x)));root.innerHTML=Object.entries(groups).map(([group,items])=>`<div class="pack-group"><p class="eyebrow">${group}</p>${items.length?items.map(x=>`<div class="pack-item ${x.checked?'checked':''}"><input type="checkbox" ${x.checked?'checked':''} onchange="checkItem(${x.id})"><span>${x.text}</span><button onclick="removeCheck(${x.id})">×</button></div>`).join(''):'<div class="empty-state" style="padding:14px;margin-bottom:10px">No items in this section yet.</div>'}</div>`).join('')}
function render(){renderTrip();renderItinerary();renderCloset();renderBuilder();renderLooks();renderPacking()}
function prepareNewPiece(file,image){let s=suggest(file);editingItemId=null;pendingImage=image;$('#itemDialogEyebrow').textContent='ADD TO YOUR CLOSET';$('#itemDialogTitle').textContent='New piece';$('#itemDialogNote').textContent='Suggested from your file name — adjust anything you like.';$('#saveItem').textContent='Add to closet';$('#itemName').value=s.n;$('#itemCategory').value=s.cat;$('#itemColour').value='';$('#preview').style.backgroundImage=`url(${image})`;$('#preview').textContent='';$('#itemDialog').showModal()}
function fileData(file){return new Promise(resolve=>{let reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.readAsDataURL(file)})}
async function handleClothingFiles(event){let files=[...event.target.files];if(!files.length)return;if(files.length===1){prepareNewPiece(files[0],await fileData(files[0]));event.target.value='';return}let images=await Promise.all(files.map(fileData));files.forEach((file,i)=>{let s=suggest(file);state.clothes.unshift({id:Date.now()+i,name:s.n,category:s.cat,colour:'',image:images[i],fallback:palettes[(state.clothes.length+i)%palettes.length],packed:false})});persist();renderCloset();renderBuilder();event.target.value='';alert(`${files.length} clothing items were added. Use the ✎ button on any item to update its details.`)}
setTimeout(()=>{$('#fileInput').onchange=handleClothingFiles},0)
function showScreen(id){$$('.screen').forEach(screen=>screen.classList.toggle('active',screen.id===id));$$('.top-tab').forEach(tab=>tab.classList.toggle('active',tab.dataset.screen===id));window.scrollTo({top:0,behavior:'smooth'})}
$$('.top-tab').forEach(tab=>tab.onclick=()=>showScreen(tab.dataset.screen))
async function getWeather(){if(!state.trip?.destination)return;try{let geo=await fetch(`https://geocoding-api.open-meteo.com/v1/search?name=${encodeURIComponent(state.trip.destination)}&count=1&language=en&format=json`).then(r=>r.json()),place=geo.results?.[0];if(!place)throw Error('No place');let maxDate=new Date();maxDate.setDate(maxDate.getDate()+16);let start=state.trip.start,end=state.trip.end;if(new Date(start)>maxDate)return;let limit=new Date(Math.min(new Date(end+'T12:00'),maxDate));let data=await fetch(`https://api.open-meteo.com/v1/forecast?latitude=${place.latitude}&longitude=${place.longitude}&daily=weather_code,temperature_2m_max&timezone=auto&start_date=${start}&end_date=${dayKey(limit)}`).then(r=>r.json());state.trip.weather={};(data.daily?.time||[]).forEach((date,i)=>{let code=data.daily.weather_code[i],icons=code<=1?'☀':code<=3?'☼':code<=67?'☁':'☂';state.trip.weather[date]={t:Math.round(data.daily.temperature_2m_max[i]),icon:icons}});persist();renderItinerary();$('#weatherHeadline').textContent=`Live forecast loaded for ${place.name}.`}catch{ $('#weatherHeadline').textContent='Typical weather is shown for your trip.' }}
function openTripDialog(edit=false){let trip=edit?state.trip:null;$('#tripDialog').querySelector('.eyebrow').textContent=trip?'UPDATE YOUR TRIP':'START A NEW PLAN';$('#tripDialog').querySelector('h2').textContent=trip?'Edit your trip':'Where are you headed?';$('#saveTrip').textContent=trip?'Save trip changes':'Create itinerary';$('#tripName').value=trip?.name||'';$('#tripDestination').value=trip?.destination||'';$('#tripStart').value=trip?.start||'';$('#tripEnd').value=trip?.end||'';$('#tripError').textContent='Trips can be from 2 to 90 days.';$('#tripError').className='form-note';$('#tripDialog').showModal()}
function saveTrip(){let name=$('#tripName').value.trim(),destination=$('#tripDestination').value.trim(),start=$('#tripStart').value,end=$('#tripEnd').value,err=$('#tripError'),days=(new Date(end+'T12:00')-new Date(start+'T12:00'))/864e5+1;if(!name||!destination||!start||!end||days<2||days>90){event.preventDefault();err.textContent='Please enter a trip between 2 and 90 days.';err.className='form-note error';return}let schedule=Object.fromEntries(Object.entries(state.trip?.schedule||{}).filter(([date])=>date>=start&&date<=end));state.trip={name,destination,start,end,schedule,weather:{}};persist();render();getWeather()}
function savePiece(){let name=$('#itemName').value.trim();if(!name){event.preventDefault();return}if(editingItemId){let item=piece(editingItemId);Object.assign(item,{name,category:$('#itemCategory').value,colour:$('#itemColour').value.trim(),image:pendingImage||item.image});editingItemId=null}else state.clothes.unshift({id:Date.now(),name,category:$('#itemCategory').value,colour:$('#itemColour').value.trim(),image:pendingImage,fallback:palettes[state.clothes.length%palettes.length],packed:false});pendingImage='';persist();renderCloset();renderBuilder()}
function openAssign(key){if(!state.trip)return;assigning=key;let options=state.looks.map(l=>`<option value="${l.id}">${l.name}</option>`).join('');if(!options){selected=[];$('#lookName').value='';location.hash='builder';return}$('#assignLookSelect').innerHTML=options;$('#assignDate').innerHTML=dateList().map(d=>`<option value="${dayKey(d)}" ${dayKey(d)===key?'selected':''}>${formatDate(d)}</option>`).join('');$('#assignDialog').showModal()}
function confirmAssign(){state.trip.schedule[$('#assignDate').value]={lookId:Number($('#assignLookSelect').value)};persist();renderItinerary()}
function suggest(file){let n=file.name.replace(/[-_]/g,' ').replace(/\.[^.]+$/,'').trim(),s=n.toLowerCase(),cat=s.includes('dress')?'dress':s.match(/pants|jean|skirt|short|trouser/)?'bottom':s.match(/shoe|boot|sandal|heel|sneaker/)?'shoe':s.match(/jacket|coat|blazer|cardigan/)?'outerwear':s.match(/bag|belt|hat|scarf|jewel/)?'accessory':'top';return {n:n.replace(/\b\w/g,c=>c.toUpperCase()),cat}}
function autoPlan(){if(!state.trip)return $('#tripDialog').showModal();let available=state.looks;if(!available.length){let tops=state.clothes.filter(x=>x.category==='top'),bottoms=state.clothes.filter(x=>x.category==='bottom'),dresses=state.clothes.filter(x=>x.category==='dress'),shoes=state.clothes.filter(x=>x.category==='shoe');for(let i=0;i<Math.max(1,Math.min(5,tops.length+ dresses.length));i++){let ids=(dresses[i%dresses.length]?[dresses[i%dresses.length]?.id]:[tops[i%tops.length]?.id,bottoms[i%bottoms.length]?.id]).filter(Boolean);if(shoes.length)ids.push(shoes[i%shoes.length].id);if(ids.length)state.looks.push({id:Date.now()+i,name:`Suggested look ${i+1}`,pieces:ids,packed:false})}available=state.looks}dateList().forEach((d,i)=>{let k=dayKey(d);if(!state.trip.schedule[k]&&available.length)state.trip.schedule[k]={lookId:available[i%available.length].id}});persist();render()}
function pick(id){let x=piece(id),old=selected.findIndex(y=>piece(y)?.category===x.category);if(selected.includes(id))selected=selected.filter(x=>x!==id);else{if(old>=0)selected.splice(old,1);selected.push(id)}renderBuilder()}
function loadLook(id){selected=[...state.looks.find(l=>l.id===id).pieces];$('#lookName').value=state.looks.find(l=>l.id===id).name;renderBuilder();location.hash='builder'}
function markLookPacked(id){let l=state.looks.find(x=>x.id===id);l.packed=!l.packed;l.pieces.forEach(id=>{let p=piece(id);if(p)p.packed=l.packed});persist();render()}
function clearDay(k){delete state.trip.schedule[k];persist();renderItinerary()}
function editPiece(id){let item=piece(id);editingItemId=id;pendingImage=item.image||'';$('#itemDialogEyebrow').textContent='UPDATE YOUR CLOSET';$('#itemDialogTitle').textContent='Edit piece';$('#itemDialogNote').textContent='Update the details, then save your changes.';$('#saveItem').textContent='Save changes';$('#itemName').value=item.name;$('#itemCategory').value=item.category;$('#itemColour').value=item.colour||'';$('#preview').style.backgroundImage=img(item);$('#preview').textContent='';$('#itemDialog').showModal()}
function removePiece(id){state.clothes=state.clothes.filter(x=>x.id!==id);selected=selected.filter(x=>x!==id);persist();renderCloset();renderBuilder()}
function togglePacked(id){piece(id).packed=!piece(id).packed;persist();renderCloset();renderReadiness()}
function checkItem(id){let x=state.checklist.find(x=>x.id===id);x.checked=!x.checked;persist();renderPacking()}
function removeCheck(id){state.checklist=state.checklist.filter(x=>x.id!==id);persist();renderPacking()}
function openBulkDialog(){let groups=state.packingSections;$('#bulkSection').innerHTML=groups.map(x=>`<option value="${x}">${x}</option>`).join('');$('#bulkItems').value='';$('#bulkDialog').showModal()}
function saveSection(){let name=$('#sectionName').value.trim();if(!name){event.preventDefault();return}if(!state.packingSections.some(x=>x.toLowerCase()===name.toLowerCase()))state.packingSections.push(name);$('#sectionName').value='';persist();renderPacking()}
function saveBulkItems(){let group=$('#bulkSection').value,items=$('#bulkItems').value.split('\n').map(x=>x.trim()).filter(Boolean);if(!items.length){event.preventDefault();return}items.forEach((text,i)=>state.checklist.push({id:Date.now()+i,group,text,checked:false}));persist();renderPacking()}
window.openAssign=openAssign;window.markLookPacked=markLookPacked;window.clearDay=clearDay;window.pick=pick;window.loadLook=loadLook;window.editPiece=editPiece;window.removePiece=removePiece;window.togglePacked=togglePacked;window.checkItem=checkItem;window.removeCheck=removeCheck;
setTimeout(()=>{$('#addChecklist').onclick=openBulkDialog;$('#addSection').onclick=()=>$('#sectionDialog').showModal();$('#saveSection').onclick=saveSection;$('#saveBulkItems').onclick=saveBulkItems;$('#newTrip').onclick=()=>openTripDialog(false);$('#editTrip').onclick=()=>openTripDialog(true)},0)
setTimeout(()=>{let dialog=$('#tripDialog'),close=dialog.querySelector('.x');close.type='button';close.onclick=()=>dialog.close();let save=$('#saveTrip');if(!save.parentElement.classList.contains('trip-actions')){let actions=document.createElement('div');actions.className='trip-actions';actions.style.cssText='display:flex;gap:8px;margin-top:10px';let cancel=document.createElement('button');cancel.type='button';cancel.className='outline';cancel.textContent='Cancel';cancel.style.flex='1';cancel.onclick=()=>dialog.close();save.parentNode.insertBefore(actions,save);actions.append(cancel,save);save.style.flex='2';save.style.marginTop='0'}},0)
$('#newTrip').onclick=$('#editTrip').onclick=()=>$('#tripDialog').showModal();$('#saveTrip').onclick=saveTrip;$('#autoPlan').onclick=autoPlan;$('#printPlan').onclick=()=>window.print();$('#addItem').onclick=()=>$('#fileInput').click();$('#fileInput').onchange=e=>{let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{pendingImage=r.result;let s=suggest(f);$('#itemName').value=s.n;$('#itemCategory').value=s.cat;$('#preview').style.backgroundImage=`url(${pendingImage})`;$('#preview').textContent='';$('#itemDialog').showModal()};r.readAsDataURL(f)};$('#saveItem').onclick=savePiece;$('#randomize').onclick=()=>{let by=Object.values(state.clothes.reduce((a,x)=>((a[x.category]??=[]).push(x),a),{}));selected=by.map(a=>a[Math.floor(Math.random()*a.length)].id);renderBuilder()};$('#saveLook').onclick=()=>{if(!selected.length)return;state.looks.push({id:Date.now(),name:$('#lookName').value.trim()||'Untitled look',pieces:[...selected],packed:false});persist();renderLooks();$('#lookName').value=''};$('#assignLook').onclick=()=>{if(selected.length){let l={id:Date.now(),name:$('#lookName').value.trim()||'Untitled look',pieces:[...selected],packed:false};state.looks.push(l);persist();renderLooks()}openAssign(dateList()[0]?dayKey(dateList()[0]):'')};$('#confirmAssign').onclick=confirmAssign;$('#addChecklist').onclick=()=>{let t=prompt('Add a packing item');if(t?.trim()){state.checklist.push({id:Date.now(),text:t.trim(),checked:false});persist();renderPacking()}};$$('#filters button').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;$$('#filters button').forEach(x=>x.classList.toggle('active',x===b));renderCloset()});
render();
